---
deployment:
  tasks:
    - export DEPLOYPATH=/home/conicet/public_html/prueba
    #- export REPOPATH=/home/conicet/repositories/intermardel
    #- /bin/cp -R intranet $DEPLOYPATH
    - /bin/cp -R intranet/!(recibosRetencion|ad_pdf) $DEPLOYPATH
